apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-sysdso
  namespace: sistema
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-sysdso
  template:
    metadata:
      labels:
          app: postgres-sysdso
    spec:
      containers:
        # container do banco da biblioteca
        - name: bd-sysdso
          image: postgres:alpine
          ports:
            - containerPort:
              valueFrom: POSTGRES_PORT             
          volumeMounts:
            - name: postgresdb
              mountPath: /var/lib/postgresql/data
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_HOST
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
      
      volumes:
        - name: postgresdb
          persistentVolumeClaim:
            claimName: postgres-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: sistema
spec:
  type: ClusterIP
  ports:
  - name: "postgres-svc"
    port: 5432
    targetPort: 5432