# Generated by Django 4.2.13 on 2024-05-09 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguranca', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aplicacao',
            name='abrangencia',
        ),
        migrations.RemoveField(
            model_name='aplicacao',
            name='area_responsavel',
        ),
        migrations.RemoveField(
            model_name='aplicacao',
            name='arquitetura',
        ),
        migrations.RemoveField(
            model_name='aplicacao',
            name='essencial',
        ),
        migrations.RemoveField(
            model_name='aplicacao',
            name='estrategico',
        ),
        migrations.RemoveField(
            model_name='aplicacao',
            name='gestor_negocial',
        ),
        migrations.RemoveField(
            model_name='aplicacao',
            name='hospedagem',
        ),
        migrations.AlterField(
            model_name='aplicacao',
            name='data_descontinuacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data descontinuação'),
        ),
        migrations.AlterField(
            model_name='aplicacao',
            name='token_acesso',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Token de acesso'),
        ),
    ]
