# Generated by Django 4.2.13 on 2024-05-12 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguranca', '0002_remove_aplicacao_abrangencia_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aplicacao',
            options={'ordering': ['nome'], 'permissions': [('can_view_aplicacao', 'Can view aplicações'), ('can_change_aplicacao', 'Can change aplicações'), ('can_add_aplicacao', 'Can add aplicações'), ('can_delete_aplicacao', 'Can delete aplicações')], 'verbose_name': 'Aplicação', 'verbose_name_plural': 'Aplicações'},
        ),
        migrations.AlterModelOptions(
            name='areanegocial',
            options={'ordering': ['nome'], 'permissions': [('can_view_area_negocial', 'Can view areas negociais'), ('can_change_area_negocial', 'Can change areas negociais'), ('can_add_area_negocial', 'Can add areas negociais'), ('can_delete_area_negocial', 'Can delete areas negociais')], 'verbose_name': 'Área Negocial', 'verbose_name_plural': 'Áreas Negociais'},
        ),
        migrations.AlterModelOptions(
            name='ativoinfraestrutura',
            options={'ordering': ['tipo', 'nome'], 'permissions': [('can_view_ativo_infraestrutura', 'Can view ativos infraestrutura'), ('can_change_ativo_infraestrutura', 'Can change ativos infraestrutura'), ('can_add_ativo_infraestrutura', 'Can add ativos infraestrutura'), ('can_delete_ativo_infraestrutura', 'Can delete ativos infraestrutura')], 'verbose_name': 'Ativo de Infraestrutura', 'verbose_name_plural': 'Ativos de Infraestrutura'},
        ),
        migrations.AlterModelOptions(
            name='resultadoscan',
            options={'ordering': ['aplicacao', 'data_resultado'], 'permissions': [('can_view_resultado_scan', 'Can view resultados scan'), ('can_change_resultado_scan', 'Can change resultados scan'), ('can_add_resultado_scan', 'Can add resultados scan'), ('can_delete_resultado_scan', 'Can delete resultados scan')], 'verbose_name': 'Resultado da Varredura', 'verbose_name_plural': 'Resultados da Varredura'},
        ),
        migrations.AlterModelOptions(
            name='tipoaplicacao',
            options={'ordering': ['nome'], 'permissions': [('can_view_tipo_aplicacao', 'Can view tipos aplicação'), ('can_change_tipo_aplicacao', 'Can change tipos aplicação'), ('can_add_tipo_aplicacao', 'Can add tipos aplicação'), ('can_delete_tipo_aplicacao', 'Can delete tipos aplicação')], 'verbose_name': 'Tipo de aplicação', 'verbose_name_plural': 'Tipos de aplicação'},
        ),
        migrations.AlterModelOptions(
            name='tipoativoinfraestrutura',
            options={'ordering': ['nome'], 'permissions': [('can_view_tipo_ativo_infraestrutura', 'Can view tipos ativos infraestrutura'), ('can_change_tipo_ativo_infraestrutura', 'Can change tipos ativos infraestrutura'), ('can_add_tipo_ativo_infraestrutura', 'Can add tipos ativos infraestrutura'), ('can_delete_tipo_ativo_infraestrutura', 'Can delete tipos ativos infraestrutura')], 'verbose_name': 'Tipo de Ativo de Infraestrutura', 'verbose_name_plural': 'Tipos de Ativos de Infraestrutura'},
        ),
        migrations.AlterModelOptions(
            name='versaoaplicacao',
            options={'ordering': ['aplicacao', 'numero_versao'], 'permissions': [('can_view_versao_aplicacao', 'Can view versões aplicação'), ('can_change_versao_aplicacao', 'Can change versões aplicação'), ('can_add_versao_aplicacao', 'Can add versões aplicação'), ('can_delete_versao_aplicacao', 'Can delete versões aplicação')], 'verbose_name': 'Versão da Aplicação', 'verbose_name_plural': 'Versões da Aplicação'},
        ),
        migrations.AlterField(
            model_name='versaoaplicacao',
            name='aplicacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versoes', to='seguranca.aplicacao'),
        ),
    ]
