# Generated by Django 4.2.13 on 2024-05-16 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguranca', '0003_alter_aplicacao_options_alter_areanegocial_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aplicacao',
            name='aplicacao_pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seguranca.aplicacao', verbose_name='Aplicação pai'),
        ),
    ]
