# Generated by Django 4.2.13 on 2024-05-16 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguranca', '0004_alter_aplicacao_aplicacao_pai'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoVarredura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(max_length=1000, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Tipo de Varredura',
                'verbose_name_plural': 'Tipos de Varredura',
                'db_table': 'tb_tipo_varredura',
                'ordering': ['nome'],
                'permissions': [('can_view_tipo_varredura', 'Can view tipos varredura'), ('can_change_tipo_varredura', 'Can change tipos varredura'), ('can_add_tipo_varredura', 'Can add tipos varredura'), ('can_delete_tipo_varredura', 'Can delete tipos varredura')],
            },
        ),
        migrations.AlterField(
            model_name='resultadoscan',
            name='aplicacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguranca.versaoaplicacao', verbose_name='Aplicação'),
        ),
        migrations.CreateModel(
            name='SistemaVarredura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(max_length=1000, verbose_name='Descrição')),
                ('url', models.URLField(verbose_name='URL')),
                ('usuario', models.CharField(blank=True, max_length=50, null=True, verbose_name='Usuário')),
                ('senha', models.CharField(blank=True, max_length=50, null=True, verbose_name='Senha')),
                ('token', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Token')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguranca.tipovarredura', verbose_name='Tipo de Varredura')),
            ],
            options={
                'verbose_name': 'Sistema de Varredura',
                'verbose_name_plural': 'Sistemas de Varredura',
                'db_table': 'tb_sistema_varredura',
                'ordering': ['tipo', 'nome'],
                'permissions': [('can_view_sistema_varredura', 'Can view sistemas varredura'), ('can_change_sistema_varredura', 'Can change sistemas varredura'), ('can_add_sistema_varredura', 'Can add sistemas varredura'), ('can_delete_sistema_varredura', 'Can delete sistemas varredura')],
            },
        ),
    ]
