# Generated by Django 4.2.13 on 2024-05-16 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguranca', '0005_tipovarredura_alter_resultadoscan_aplicacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistemavarredura',
            name='status',
            field=models.CharField(choices=[['ATIVO', 'Ativo'], ['DESATIVADO', 'Desativado'], ['EM MANUTENÇÃO', 'Em manutenção']], default='ATIVO', max_length=20, verbose_name='Situação'),
        ),
    ]
