# Generated by Django 4.2.13 on 2024-05-16 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguranca', '0006_sistemavarredura_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistemavarredura',
            name='aplicacoes',
            field=models.ManyToManyField(blank=True, related_name='sistemas_varredura', to='seguranca.versaoaplicacao'),
        ),
        migrations.AddField(
            model_name='versaoaplicacao',
            name='varreduras',
            field=models.ManyToManyField(blank=True, related_name='versoes', to='seguranca.sistemavarredura'),
        ),
    ]
