# Generated by Django 4.2.13 on 2024-05-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguranca', '0007_sistemavarredura_aplicacoes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='versaoaplicacao',
            old_name='varreduras',
            new_name='sistema_varreduras',
        ),
        migrations.AddField(
            model_name='sistemavarredura',
            name='tipos_varreduras',
            field=models.ManyToManyField(blank=True, related_name='tipos_sistemas_varredura', to='seguranca.tipovarredura'),
        ),
        migrations.AddField(
            model_name='tipovarredura',
            name='sistemas_varredura',
            field=models.ManyToManyField(blank=True, related_name='tipos_varredura', to='seguranca.sistemavarredura'),
        ),
    ]
