# Generated by Django 4.2.13 on 2024-05-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguranca', '0008_rename_varreduras_versaoaplicacao_sistema_varreduras_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sistemavarredura',
            name='tipos_varreduras',
            field=models.ManyToManyField(blank=True, related_name='sistema_varredura', to='seguranca.tipovarredura'),
        ),
    ]
