# Generated by Django 4.2.13 on 2024-06-24 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguranca', '0009_alter_sistemavarredura_tipos_varreduras'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='versaoaplicacao',
            options={'ordering': ['aplicacao', 'nome_versao'], 'permissions': [('can_view_versao_aplicacao', 'Can view versões aplicação'), ('can_change_versao_aplicacao', 'Can change versões aplicação'), ('can_add_versao_aplicacao', 'Can add versões aplicação'), ('can_delete_versao_aplicacao', 'Can delete versões aplicação')], 'verbose_name': 'Versão da Aplicação', 'verbose_name_plural': 'Versões da Aplicação'},
        ),
        migrations.RenameField(
            model_name='versaoaplicacao',
            old_name='numero_versao',
            new_name='nome_versao',
        ),
        migrations.AddField(
            model_name='aplicacao',
            name='area_responsavel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seguranca.areanegocial', verbose_name='Área responsável'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aplicacao',
            name='arquitetura',
            field=models.CharField(choices=[['WEB', 'Web'], ['CLIENTE/SERVIDOR', 'Cliente/Servidor'], ['MAINFRAME', 'Mainframe']], default='WEB', max_length=20, verbose_name='Arquitetura'),
        ),
        migrations.AddField(
            model_name='aplicacao',
            name='hospedagem',
            field=models.CharField(choices=[['LOCAL', 'Local'], ['CLOUD', 'Cloud'], ['HÍBRIDO', 'Híbrido'], ['EXTERNO', 'Externo']], default='LOCAL', max_length=20, verbose_name='Hospedagem'),
        ),
        migrations.AlterUniqueTogether(
            name='versaoaplicacao',
            unique_together={('aplicacao', 'nome_versao')},
        ),
    ]
