# Generated by Django 4.2.13 on 2024-07-03 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguranca', '0012_alter_sistemavarredura_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipovarredura',
            name='sistemas_varredura',
        ),
    ]
