# Generated by Django 4.2.13 on 2024-07-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguranca', '0013_remove_tipovarredura_sistemas_varredura'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resultadoscan',
            options={'ordering': ['aplicacao', '-data_resultado'], 'permissions': [('can_view_resultado_scan', 'Can view resultados scan'), ('can_change_resultado_scan', 'Can change resultados scan'), ('can_add_resultado_scan', 'Can add resultados scan'), ('can_delete_resultado_scan', 'Can delete resultados scan')], 'verbose_name': 'Resultado da Varredura', 'verbose_name_plural': 'Resultados da Varredura'},
        ),
        migrations.AddField(
            model_name='resultadoscan',
            name='sistema_varredura',
            field=models.CharField(default=1, max_length=50, verbose_name='Sistema de varrredura'),
            preserve_default=False,
        ),
    ]
