# Generated by Django 4.2.13 on 2024-07-16 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguranca', '0017_alter_rede_dns_secundario'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistemavarredura',
            name='usa_webhook',
            field=models.BooleanField(default=False, verbose_name='Usa Webhook'),
        ),
    ]
