# Generated by Django 4.2.13 on 2024-09-18 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguranca', '0018_sistemavarredura_usa_webhook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aplicacao',
            name='bancos_dados',
        ),
        migrations.RemoveField(
            model_name='aplicacao',
            name='servicos',
        ),
        migrations.RemoveField(
            model_name='aplicacao',
            name='servidores',
        ),
        migrations.RemoveField(
            model_name='bancodados',
            name='aplicacoes',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='servidor',
        ),
        migrations.RemoveField(
            model_name='servidor',
            name='aplicacoes',
        ),
        migrations.AddField(
            model_name='aplicacao',
            name='ativo_infra_app',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seguranca.ativoinfraestrutura', verbose_name='Ativo de Infraestrutura'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bancodados',
            name='ativo_infra_db',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seguranca.ativoinfraestrutura', verbose_name='Ativo de Infraestrutura'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servico',
            name='ativo_infra_svc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seguranca.ativoinfraestrutura', verbose_name='Ativo de Infraestrutura'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servidor',
            name='ativo_infra_srv',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seguranca.ativoinfraestrutura', verbose_name='Ativo de Infraestrutura'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='versaoaplicacao',
            name='bancos_dados',
            field=models.ManyToManyField(blank=True, related_name='aplicacoes_banco_dados', to='seguranca.bancodados'),
        ),
        migrations.AddField(
            model_name='versaoaplicacao',
            name='servicos',
            field=models.ManyToManyField(blank=True, related_name='aplicacoes_servico', to='seguranca.servico'),
        ),
        migrations.AddField(
            model_name='versaoaplicacao',
            name='servidores',
            field=models.ManyToManyField(blank=True, related_name='aplicacoes_servidor', to='seguranca.servidor'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='aplicacoes',
            field=models.ManyToManyField(blank=True, related_name='servico_aplicacoes', to='seguranca.versaoaplicacao'),
        ),
    ]
