# Generated by Django 4.2.13 on 2024-11-13 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguranca', '0020_arquivoconfiguracao_configuracao_relacionamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracao',
            name='senha_servico',
        ),
        migrations.RemoveField(
            model_name='configuracao',
            name='token_acesso',
        ),
        migrations.RemoveField(
            model_name='configuracao',
            name='url_acesso',
        ),
        migrations.AddField(
            model_name='versaoaplicacao',
            name='senha_servico',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Senha de serviço'),
        ),
        migrations.AddField(
            model_name='versaoaplicacao',
            name='token_acesso',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Token de acesso'),
        ),
        migrations.AddField(
            model_name='versaoaplicacao',
            name='url_acesso',
            field=models.URLField(blank=True, null=True, verbose_name='URL de acesso à aplicação'),
        ),
        migrations.AlterField(
            model_name='aplicacao',
            name='usuario_servico',
            field=models.CharField(default='servico', max_length=50, verbose_name='Usuário de serviço'),
        ),
    ]
