# Generated by Django 4.2.13 on 2024-12-23 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguranca', '0021_remove_configuracao_senha_servico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bancodados',
            name='senha',
        ),
        migrations.RemoveField(
            model_name='bancodados',
            name='usuario',
        ),
        migrations.AddField(
            model_name='bancodados',
            name='ambiente',
            field=models.CharField(choices=[['PRODUÇÃO', 'Produção'], ['HOMOLOGAÇÃO', 'Homologação'], ['DESENVOLVIMENTO', 'Desenvolvimento'], ['TESTE', 'Teste'], ['BUGFIX', 'Bugfix'], ['TREINAMENTO', 'Treinamento'], ['OUTRO', 'Outro']], default='DESENVOLVIMENTO', max_length=50, verbose_name='Ambiente'),
        ),
        migrations.AddField(
            model_name='bancodados',
            name='nome',
            field=models.CharField(default=1, max_length=100, unique=True, verbose_name='Nome do banco de dados'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bancodados',
            name='porta',
            field=models.IntegerField(default=1521, verbose_name='Porta'),
        ),
        migrations.AlterField(
            model_name='bancodados',
            name='ativo_infraestrutura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seguranca.ativoinfraestrutura', verbose_name='Ativo de Infraestrutura'),
        ),
        migrations.AlterField(
            model_name='bancodados',
            name='versao',
            field=models.TextField(default='1.0', max_length=50, null=True, verbose_name='Versão'),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='ambiente',
            field=models.CharField(choices=[['PRODUÇÃO', 'Produção'], ['HOMOLOGAÇÃO', 'Homologação'], ['DESENVOLVIMENTO', 'Desenvolvimento'], ['TESTE', 'Teste'], ['BUGFIX', 'Bugfix'], ['TREINAMENTO', 'Treinamento'], ['OUTRO', 'Outro']], default='DESENVOLVIMENTO', max_length=50, verbose_name='Ambiente'),
        ),
    ]
