# Generated by Django 4.2.13 on 2024-12-28 21:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('seguranca', '0022_remove_bancodados_senha_remove_bancodados_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='nome',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, unique=True, verbose_name='Nome do servidor'),
            preserve_default=False,
        ),
    ]
