# Generated by Django 4.2.13 on 2024-12-28 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguranca', '0023_servidor_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aplicacao',
            name='sigla',
            field=models.CharField(max_length=20, verbose_name='Sigla'),
        ),
        migrations.AlterField(
            model_name='aplicacao',
            name='url_codigo_fonte',
            field=models.URLField(max_length=500, verbose_name='URL Fonte'),
        ),
    ]
