# Generated by Django 4.2.13 on 2025-01-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguranca', '0024_alter_aplicacao_sigla_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rede',
            name='ativo_infraestrutura',
        ),
        migrations.AddField(
            model_name='rede',
            name='ativos_infraestrutura',
            field=models.ManyToManyField(blank=True, related_name='redes', to='seguranca.ativoinfraestrutura'),
        ),
        migrations.AlterField(
            model_name='bancodados',
            name='versao',
            field=models.TextField(max_length=50, null=True, verbose_name='Versão'),
        ),
    ]
