version: "3"

services:
  # sonarqube - para fazer verificação de código fonte (SAST)
  sonar:
    image: sonarqube:lts-community  
    container_name: sonar-mandso
    ports:
      - "9000:9000"
    volumes:
      - sonar_data:/opt/sonarqube/data
      - sonar_extensions:/opt/sonarqube/extensions
      - sonar_logs:/opt/sonarqube/logs

volumes:
  sonar_data:
  sonar_extensions:
  sonar_logs:

