version: "3"

services:
  # sonarqube - para fazer verificação de código fonte (SAST)
  sonar:
    image: sonarqube:lts-community  
    container_name: sonar
    volumes:
      - sonar_data:/opt/sonarqube/data
      - sonar_extensions:/opt/sonarqube/extensions
      - sonar_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"

  # SonarQube CLI - para fazer análise de código fonte atraves de linha de comando
  sonar_cli:
    build: ./sonar_cli/.
    container_name: sonar_cli

  # OWASP Dependency Check - para fazer verificação de dependências
  owasp_dc:
    image: owasp/dependency-check
    container_name: owasp_dc
    volumes:
      - owasp-dc:/src
    command: "--scan /src --format 'ALL' --out /src/report"

  # OWASP ZAP - para fazer verificação de segurança DAST
  owasp_zap:
    #image="zaproxy/zap-bare:2.14.0",       # usando esta imagem para fins de teste, porque é mais leve (é muito restrita)
    image: "zaproxy/zap-stable"
    volumes: 
      - owasp_zap:/zap/wrk
    command: "zap.sh -daemon -config api.disablekey=true"

  # banco de dados para a aplicação de segurança
  pg_appseg:
    image: postgres:alpine
    container_name: pg-appseg
    environment:
      POSTGRES_DB: appseg
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      LANG: pt_BR.UTF8
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # aplicação de gerenciamento de segurança
  appseg:
    build: ./appseg/.
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: appseg
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "8000:8000"
    command: "python manage.py runserver 0.0.0.0:8000"
  
volumes:
  sonar_data:
  sonar_extensions:
  sonar_logs:
  owasp-dc:
  owasp_zap:
  postgres_data:
  
